//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__CheckSum 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CheckSum *pCmd;
  } CltChCmd__CheckSum;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient 
  {
    CMDMETH *pMeth;
    _FSM_TCPIP_CLIENT dData;
    SVRDSC *pDsc;
  } SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient;

typedef struct CltChCmd__TCPIPClient 
  {
    struct SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient *pCh;
    _FSM_TCPIP_CLIENT dData;
    _TCPIPClient *pCmd;
  } CltChCmd__TCPIPClient;

typedef struct CltChCmd_IXON_LoggerAPI_Interface 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    IXON_LoggerAPI_Interface *pCmd;
  } CltChCmd_IXON_LoggerAPI_Interface;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_RAMex 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RAMex *pCmd;
  } CltChCmd_RAMex;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_VirtualBaseInit 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    VirtualBaseInit *pCmd;
  } CltChCmd_VirtualBaseInit;

typedef struct SvrCh__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient 
  {
    CHMETH *pMeth;
    _FSM_TCPIP_CLIENT dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient;

typedef struct SvrCh__STATE_TCPIPC_INTF_PTofCls__TCPIPClientInterface 
  {
    CHMETH *pMeth;
    _STATE_TCPIPC_INTF dData;
    SVRDSC *pDsc;
  } SvrCh__STATE_TCPIPC_INTF_PTofCls__TCPIPClientInterface;

typedef struct SvrCh_teUSER_TCP_STEPS_PTofCls_IXON_LoggerAPI_Interface 
  {
    CHMETH *pMeth;
    teUSER_TCP_STEPS dData;
    SVRDSC *pDsc;
  } SvrCh_teUSER_TCP_STEPS_PTofCls_IXON_LoggerAPI_Interface;

