//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SvrCh_DINT : STRUCT
    pMeth : ^CHMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_DINT : STRUCT
    pCh : ^SvrCh_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_UDINT : STRUCT
    pMeth : ^CHMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_UDINT : STRUCT
    pCh : ^SvrCh_UDINT;
    dData : UDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd_DINT : STRUCT
    pMeth : ^CMDMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__CheckSum : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_CheckSum;
  END_STRUCT;
  CltChCmd__MultiTask : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_MultiTask;
  END_STRUCT;
  CltChCmd__StdLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_StdLib;
  END_STRUCT;
  CltChCmd__TaskObjectControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_TaskObjectControl;
  END_STRUCT;
  SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient : STRUCT
    pMeth : ^CMDMETH;
    dData : _TCPIPClient::_FSM_TCPIP_CLIENT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__TCPIPClient : STRUCT
    pCh : ^SvrChCmd__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient;
    dData : _TCPIPClient::_FSM_TCPIP_CLIENT;
    pCmd : ^_TCPIPClient;
  END_STRUCT;
  CltChCmd_IXON_LoggerAPI_Interface : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^IXON_LoggerAPI_Interface;
  END_STRUCT;
  SvrChCmd_UDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_MerkerEx : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^MerkerEx;
  END_STRUCT;
  CltChCmd_RAMex : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RAMex;
  END_STRUCT;
  CltChCmd_SigCLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SigCLib;
  END_STRUCT;
  CltChCmd_String : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^String;
  END_STRUCT;
  CltChCmd_VirtualBaseInit : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^VirtualBaseInit;
  END_STRUCT;
  SvrCh__FSM_TCPIP_CLIENT_PTofCls__TCPIPClient : STRUCT
    pMeth : ^CHMETH;
    dData : _TCPIPClient::_FSM_TCPIP_CLIENT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__STATE_TCPIPC_INTF_PTofCls__TCPIPClientInterface : STRUCT
    pMeth : ^CHMETH;
    dData : _TCPIPClientInterface::_STATE_TCPIPC_INTF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_teUSER_TCP_STEPS_PTofCls_IXON_LoggerAPI_Interface : STRUCT
    pMeth : ^CHMETH;
    dData : IXON_LoggerAPI_Interface::teUSER_TCP_STEPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
END_TYPE
