//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#RE_IN_DE
#pragma define (store)
_TCPIPClient : CLASS_PUBLIC
#include "..\Class\_TCPIPClient\_TCPIPClient.h"
#include "..\Class\_TCPIPClient\SalamanderDelay.h"
#include "..\Class\_TCPIPClient\lsl_st_ssl_user.h"
	TYPE
	  _FSM_TCPIP_CLIENT :
	  (
	    _STATE_NONE,
	    _STATE_INIT_SERVER,
	    _STATE_NO_USER_INTERFACE_CONNECTED,
	    _STATE_IDLE,
	    _STATE_MAIN_SOCK,
	    _STATE_LISTEN,
	    _STATE_ACCEPT,
	    _STATE_CONNECT,
	    _STATE_RECV,
	    _STATE_SHUTDOWN,
	    _STATE_CLOSE_MAIN_SOCK,
	    _STATE_CLOSE_SOCK,
	    _STATE_ERROR,
	    _STATE_ERROR_ALLOCATING_MEMORY,
	    _STATE_ERROR_CREATING_MUTEX,
	    _STATE_ERROR_CREATING_TASK,
	    _STATE_SEND,
	    _STATE_MAIN_SOCK_OPT,
	    _STATE_DEL_CONNECTION,
	    _STATE_CONN_SOCK_OPT
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
_TCPIPClientInterface : CLASS_PUBLIC
	TYPE
	  _STATE_TCPIPC_INTF :
	  (
	    _STATE_NO_CONNECTION,
	    _STATE_DISCONNECTED,
	    _STATE_CONNECTED
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
IXON_LoggerAPI_Interface : CLASS_PUBLIC
: _TCPIPClientInterface
	TYPE
	  teUSER_TCP_STEPS :
	  (
	    UTS_Idle,
	    UTS_Connect,
	    UTS_CheckConnect,
	    UTS_ConnectIXON,
	    UTS_WaitConnectIXON,
	    UTS_WaitData,
	    UTS_SendData,
	    UTS_WaitSendData,
	    UTS_Disconnect,
	    UTS_Error
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
MerkerEx : CLASS_PUBLIC
#include <.\lsl_st_mt.h>
	TYPE
	  Cmdm_udLength :
	  (
	    GET_DATA_PTR,
	    EXCHANGE_DATA_PTR,
	    SAVE_DATA_TO_RAMEXFILE
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
VirtualBaseInit : CLASS_PUBLIC
	TYPE
	  CmdData :
	  (
	    GET_ADD_INFO,
	    READ_DATA,
	    WRITE_DATA,
	    READ_DATA_OFF,
	    WRITE_DATA_OFF
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)

#RE_IN_DE
